### ISSUE TITLE
EXE won't open

### ISSUE THREAD

**Issue by Speedbird643** [Fragtality/Fenix2GSX#23]
I downloaded this yesterday along with all the required bits - WASM is in my Community folder, and I got hold of the appropriate .NET runtimes (reproduced below in case I missed something!). However the .exe won't load either via FSUIPC or manually in the MSFS menu. The log file seems to indicate issues generating a CEF Browser:

2023-07-19 06:57:43.979 [INF] ----------------------------------------------------------------------- 
2023-07-19 06:57:43.992 [INF] [ App:InitLog                      ] Fenix2GSX started! Log Level: Debug Log File: Fenix2GSX.log 
2023-07-19 06:57:43.997 [INF] [ App:InitSystray                  ] Creating SysTray Icon ... 
2023-07-19 06:57:44.249 [INF] [ App:InitCef                      ] Initializing Cef Browser ... 
2023-07-19 07:01:41.722 [INF] ----------------------------------------------------------------------- 
2023-07-19 07:01:41.733 [INF] [ App:InitLog                      ] Fenix2GSX started! Log Level: Debug Log File: Fenix2GSX.log 
2023-07-19 07:01:41.735 [INF] [ App:InitSystray                  ] Creating SysTray Icon ... 
2023-07-19 07:01:41.847 [INF] [ App:InitCef                      ] Initializing Cef Browser ... 
2023-07-19 09:15:05.878 [INF] ----------------------------------------------------------------------- 
2023-07-19 09:15:05.887 [INF] [ App:InitLog                      ] Fenix2GSX started! Log Level: Debug Log File: Fenix2GSX.log 
2023-07-19 09:15:05.888 [INF] [ App:InitSystray                  ] Creating SysTray Icon ... 
2023-07-19 09:15:05.996 [INF] [ App:InitCef                      ] Initializing Cef Browser ... 
2023-07-19 09:23:05.190 [INF] ----------------------------------------------------------------------- 
2023-07-19 09:23:05.199 [INF] [ App:InitLog                      ] Fenix2GSX started! Log Level: Debug Log File: Fenix2GSX.log 
2023-07-19 09:23:05.201 [INF] [ App:InitSystray                  ] Creating SysTray Icon ... 
2023-07-19 09:23:05.315 [INF] [ App:InitCef                      ] Initializing Cef Browser ... 
2023-07-19 09:31:00.848 [INF] ----------------------------------------------------------------------- 
2023-07-19 09:31:00.858 [INF] [ App:InitLog                      ] Fenix2GSX started! Log Level: Debug Log File: Fenix2GSX.log 
2023-07-19 09:31:00.859 [INF] [ App:InitSystray                  ] Creating SysTray Icon ... 
2023-07-19 09:31:00.967 [INF] [ App:InitCef                      ] Initializing Cef Browser ... 

Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Fragtality** [comment]
So it does start and directly exists again (seems from the Logs)?
Have you rebooted the PC after .NET was installed?
Maybe it is also blocked by some AV Software or Windows Security Feature? Try if an AV-Exception or unblocking helps.
```dir -Path X:\Path\to\Fenix2GSXFolder -Recurse | Unblock-File```

**Comment by Speedbird643** [comment]
If it does, nothing appears - no window, however brief. 

I have just quickly tested the system tray and it does very briefly appear in there but only if I'm very quick with the cursor as it almost immediately disappears.

I've added exceptions, and changed user permissions with no success. The system has been rebooted too.

Windows Event Viewer throws up two 'Errors' and an 'Information' when attempting to run, all approximately one second apart:

```
Application: Fenix2GSX.exe
CoreCLR Version: 7.0.923.32018
.NET Version: 7.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Unable to locate required Cef/CefSharp dependencies:
Missing:D:\MSFS Addons\Utilities\Fenix2GSX\locales\en-US.pak
Executing Assembly Path:D:\MSFS Addons\Utilities\Fenix2GSX

   at CefSharp.DependencyChecker.AssertAllDependenciesPresent(String locale, String localesDirPath, String resourcesDirPath, Boolean packLoadingDisabled, String browserSubProcessPath) in C:\projects\cefsharp\CefSharp\DependencyChecker.cs:line 281
   at CefSharp.Core.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at CefSharp.Core.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IBrowserProcessHandler browserProcessHandler)
   at CefSharp.Cef.Initialize(CefSettingsBase settings, Boolean performDependencyCheck, IBrowserProcessHandler browserProcessHandler) in C:\projects\cefsharp\CefSharp.Core\Cef.cs:line 154
   at Fenix2GSX.App.InitCef() in C:\Users\Fragtality\source\repos\Fenix2GSX-Code\Fenix2GSX\App.xaml.cs:line 93
   at Fenix2GSX.App.OnStartup(StartupEventArgs e) in C:\Users\Fragtality\source\repos\Fenix2GSX-Code\Fenix2GSX\App.xaml.cs:line 28
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Fenix2GSX.App.Main()
```

```
_Faulting application name: Fenix2GSX.exe, version: 0.3.1.6, time stamp: 0x646e274e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1928, time stamp: 0xe9af6ed4
Exception code: 0xe0434352
Fault offset: 0x0000000000064b2c
Faulting process id: 0x0x8890
Faulting application start time: 0x0x1D9BC099D716838
Faulting application path: D:\MSFS Addons\Utilities\Fenix2GSX\Fenix2GSX.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: ce186caa-3d59-4eb1-898d-741fd86b82e6
Faulting package full name: 
Faulting package-relative application ID:

```

```
Fault bucket 1696344510019014081, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Fenix2GSX.exe
P2: 0.3.1.6
P3: 646e274e
P4: KERNELBASE.dll
P5: 10.0.22621.1928
P6: e9af6ed4
P7: e0434352
P8: 0000000000064b2c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0b41f94d-5586-48bd-8c90-40f6eedce1e5.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e11b508a-510f-44ae-bfa1-8ed253dcb171.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b3cb482e-7d95-4403-b8ad-ae31939cf743.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.87788e60-75b8-4fb8-b1e0-98a870f4beaf.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4ed490ee-cb44-4962-aa78-14fb4eb1e492.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Fenix2GSX.exe_918a4bd017d59ca7665db4fb37cb76a3e76e1bc1_66a4a4dd_30408185-c0a5-4a22-93af-d643ad0a7468

Analysis symbol: 
Rechecking for solution: 0
Report Id: ce186caa-3d59-4eb1-898d-741fd86b82e6
Report Status: 268435456
Hashed bucket: 8a4593e5fb52e565978aa058205e0dc1

```

**Comment by Fragtality** [comment]
Well it is very clear, seems you did not extract all Contents of the Archive:

```
Exception Info: System.Exception: Unable to locate required Cef/CefSharp dependencies:
Missing:D:\MSFS Addons\Utilities\Fenix2GSX\locales\en-US.pak
```

**Comment by Speedbird643** [comment]
Indeed. Not sure how I managed to miss the locales folder! Thanks for the help. Got the app working now!

**Comment by Fragtality** [comment]
Great, happy flying 😃
